### PR TITLE
[OTE_SDK, Tasks] dict-serialized label schema

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 20223 ✔️

**Review by druzhkov-paul — APPROVED** [review]
SDK part looks good to me. At the same time I don't think that updating the algo-backends in the same PR is a good idea: you either have to merge this PR before PRs in submodules and reference unmerged changes in backends, or merge PRs to backends first and then they will be using non-existent SDK functionality for a while.

**Comment by Ilya-Krylov** [comment]
If we consider particular submodule as a standalone project, then yes, I agree. But who cares about standalone submodule?

PR to update SDK, PR in every submodule to update corresponding tasks to use recently updated SDK, PR to update OTE in order to store commit hashes of updated submodules which use updated SDK. Are there not too many PRs?

Task implementations should be in OTE.

**Comment by druzhkov-paul** [comment]
It matters for our devops/testers/developers who run tests.

Hm. 3 (Ok, maybe 2) vs 3 not so much of a difference, right?

Whatever.

**Pull request merged**
