### PR TITLE
Add pruning option for face detection models

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
Alexander, did you check the combinations "quantization + pruning"?
If yes, please, add the corresponding options to `template.yaml` files.

Also it would be good to check "sparsity + pruning", "quantization + sparsity + pruning" for face-detection-200 model.

**Comment by AlexanderDokuchaev** [comment]
@LeonidBeynenson No. Currently NNCF does not support export for pruning + another algorithms.

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson approve or not?

**Comment by LeonidBeynenson** [comment]
> @LeonidBeynenson No. Currently NNCF does not support export for pruning + another algorithms.

I see.

But, nevertheless, as far as I understand if you would like to expose pruning option (i.e. allow to run pruning for other teams), you should add the corresponding section to `template.yaml` files to the corresponding models.

Please, see the following section in `template.yaml` files 
```yaml
optimisations:
  nncf_quantization:
    config: compression_config.json
    default: false
  nncf_sparsity:
    config: compression_config.json
    default: false
```

I think you should add the part
```yaml
  nncf_pruning:
    config: compression_config.json
    default: false
```
2 @Ilya-Krylov : Ilya, do you agree that this should be added?

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson looks like you are right, 

@AlexanderDokuchaev could you do that?

**Comment by AlexanderDokuchaev** [comment]
@Ilya-Krylov added

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev I've recreated PR for your convenience https://github.com/openvinotoolkit/training_extensions/pull/462
Please commit there if some changes are needed.

**Comment by Ilya-Krylov** [comment]
I would close this PR. Since there is rebased one. Don't you mind?

**Comment by Ilya-Krylov** [comment]
merged another pr with changes copied from here

**Pull request closed without merging**
