### PR TITLE
[OTE_SDK_TESTS] Added unit tests for datasets.py and train_parameters.py

### PR DESCRIPTION
**Pull request by pfinashx**

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
I guess this one should be into develop, right?

**Comment by pfinashx** [comment]
> I guess this one should be into develop, right?

Yes, you are right, changed.

**Comment by Ilya-Krylov** [comment]
still draft?

**Comment by pfinashx** [comment]
Unfortunately, yes.

**Comment by Ilya-Krylov** [comment]
@pfinashx will you update or close?

**Comment by pfinashx** [comment]
This task on hold now, Let close this PR.

**Pull request closed without merging**
