### PR TITLE
update configs

### PR DESCRIPTION
**Pull request by dkustikx**
Adding missed Accuracy Checker configs for the following models:
instance-segmentation-0002
instance-segmentation-0091
instance-segmentation-0228
face-detection-0206
person-detection-0203

### CODE REVIEW

**Review by LeonidBeynenson — APPROVED** [review]

**Comment by LeonidBeynenson** [comment]
Ilya, could you merge this when CI is OK?

**Comment by LeonidBeynenson** [comment]
run tests

**Comment by LeonidBeynenson** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Pull request merged**
