### PR TITLE
Dick/anomaly label naming

### PR DESCRIPTION
**Pull request by samet-akcay**
## Changes
This PR proposes the following changes:
- Fix inconsistent label names between the task and the backend.
- Fix PyMongo `np.float32` issue by casting the predicted scores to `float`

### CODE REVIEW

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Review by druzhkov-paul — APPROVED** [review]

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
