### PR TITLE
Update d-o-r

### PR DESCRIPTION
**Pull request by sovrasov**
- Empty label handling
- Disable model status handling
- Merge with ote branch
- Resolve issue with failed training jobs

Build 18828 ✔️
Training: Finished ✔️

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
Resolve conflicts please

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Review by druzhkov-paul — APPROVED** [review]

**Comment by sovrasov** [comment]
@Ilya-Krylov @druzhkov-paul please merge, I don't have a permission for that

**Pull request merged**
