### PR TITLE
Add training code for text-recognition-0014 & 0015

### PR DESCRIPTION
**Pull request by morkovka1337**
This PR adds training code for new released text-recognition 0014 & 0015 models. New models forced to update existing code:
* Generalized export of the models
* Moved encoder & decoder wrappers to the head classes
* Updated augmentations, added pad value as parameter
* Added new custom resnet-like archutectures:
  * Resnetlike with skip connections
  * Wideer resnet (same number of channels, but less stride to produce the feature map of bigger size) 
  * Implemented Convolutional Block Attention Module. For now it does not make any improvement, but could be useful for the future experiments
* Added 2d attention text recognition head (from test-spotting)
* Implemented classification text recognition head (for the future experiments), but it could be dropped for now and added via another patch.

### CODE REVIEW

**Comment by morkovka1337** [comment]
Run tests

**Comment by morkovka1337** [comment]
run tests

**Comment by morkovka1337** [comment]
run tests

**Comment by morkovka1337** [comment]
Jenkins please retry a build

**Comment by morkovka1337** [comment]
run tests

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
