### PR TITLE
fix

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev

**Comment by AlexanderDokuchaev** [comment]
@Ilya-Krylov Does it work with 2020.1?

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev , no, let's wait until corresponding issue is fixed. I'll notify

**Comment by AlexanderDokuchaev** [comment]
@Ilya-Krylov Can be merge now?

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev not yet

**Pull request closed without merging**
