### PR TITLE
Update instance segmentation models

### PR DESCRIPTION
**Pull request by DmitriySidnev**
New models 1039, 1040 instead 0904, 0912.

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Pull request merged**
