### PR TITLE
refactored_tests

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
MOAR TESTS!

**Comment by druzhkov-paul** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson this PR removes `shell=True` as you wanted

**Review by druzhkov-paul — APPROVED** [review]

**Review by LeonidBeynenson — APPROVED** [review]
👍

**Comment by Ilya-Krylov** [comment]
rebuild build

**Comment by Ilya-Krylov** [comment]
rebuild build

**Comment by Ilya-Krylov** [comment]
hello_job/79 :heavy_check_mark:

**Pull request merged**
