### PR TITLE
Fix random seed for NNCF classification test

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Comment by aiarkinx** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by LeonidBeynenson** [comment]
2 @Ilya-Krylov : Ilya, could you merge this PR?

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
