### PR TITLE
Calculate f1_score during training

### PR DESCRIPTION
**Pull request by GalyaZalesskaya**
A small config update for `horizontal text detection model` to be able to calculate `f1 score` during training and observe it in tensorboard

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
@Daniil-Osokin Are you following us?

**Comment by Daniil-Osokin** [comment]
Definitely, for a long time. Love to see good open source contributions!

**Comment by Ilya-Krylov** [comment]
@GalyaZalesskaya Could you make so that `precision` and `recall` are available in tensorboard?

**Comment by GalyaZalesskaya** [comment]
Yes, I definitely can do it. It will change code in openvinotoolkit/mmdetection only and do not requires changes in this repository

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
