### PR TITLE
openvino support in OTE CLI demo,eval

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 20249

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 20249 ✔️

**Comment by Ilya-Krylov** [comment]
BMM 20542 🕐 
some issues were observed related to image classification, it is under investigation

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 20604 🕐

**Comment by Ilya-Krylov** [comment]
BMM 20604 ✔️

**Comment by Ilya-Krylov** [comment]
@druzhkov-paul please have a look

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
