### PR TITLE
Update models templates

### PR DESCRIPTION
**Pull request by aleksei-kashapov**

### CODE REVIEW

**Comment by aleksei-kashapov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Review by Ilya-Krylov — APPROVED** [review]

**Comment by Ilya-Krylov** [comment]
@aleksei-kashapov you have to deal with removed IS models.

**Comment by aleksei-kashapov** [comment]
run tests

**Comment by aleksei-kashapov** [comment]
> @aleksei-kashapov you have to deal with removed IS models.

Updated

**Comment by Ilya-Krylov** [comment]
As far I can see your part is ok.

**Pull request merged**
