### PR TITLE
Sb/neural machine translation

### PR DESCRIPTION
**Pull request by bes-dev**
Add Machine Translation training framework in PyTorch.

### CODE REVIEW

**Comment by bes-dev** [comment]
@snosov1 review please

**Comment by snosov1** [comment]
@Ilya-Krylov Ilya, please, take a look.

Sergey, what happened to belbes? =)

**Comment by bes-dev** [comment]
@snosov1 his way has ended (=

**Comment by Ilya-Krylov** [comment]
@bes-dev Don't you want to add a link to the main page (https://github.com/openvinotoolkit/training_extensions)?

**Comment by bes-dev** [comment]
@Ilya-Krylov Sure. Is it looks right for you now?

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
