### PR TITLE
OTE_SDK. add ModelStatus.TRAINED_NO_STATS # 2

### PR DESCRIPTION
**Pull request by leoll2**
Clone of https://github.com/openvinotoolkit/training_extensions/pull/731 but from a local branch instead of a repo fork.

> This is needed by SC, and it's the first step in the migration of ModelStatus from ote_sdk to sc_sdk.

### CODE REVIEW

**Comment by leoll2** [comment]
run ote_sdk tests

**Comment by leoll2** [comment]
e2e report [here](https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/19811/)

**Comment by druzhkov-paul** [comment]
@leoll2 Please fix coding style. See ote_sdk tests log for more details and/or configure pre-commit hook.

**Comment by leoll2** [comment]
run ote_sdk tests

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
