### PR TITLE
Update NNCF to 1.6.0

### PR DESCRIPTION
**Pull request by aleksei-kashapov**

### CODE REVIEW

**Comment by aleksei-kashapov** [comment]
@LeonidBeynenson please take a look

**Comment by aleksei-kashapov** [comment]
run tests

**Comment by LeonidBeynenson** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
please update mmdetection commit

**Comment by aleksei-kashapov** [comment]
run tests

**Comment by aleksei-kashapov** [comment]
> please update mmdetection commit

Updated

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
