### PR TITLE
changed configs, updated deep-person, changed metrics

### PR DESCRIPTION
**Pull request by kprokofi**

### CODE REVIEW

**Comment by kprokofi** [comment]
run tests

**Comment by kprokofi** [comment]
run tests

**Comment by kprokofi** [comment]
run tests

**Comment by kprokofi** [comment]
run tests

**Comment by kprokofi** [comment]
run tests

**Comment by kprokofi** [comment]
run tests

**Comment by kprokofi** [comment]
run tests

**Comment by kprokofi** [comment]
run_tests

**Comment by kprokofi** [comment]
run tests

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
