### PR TITLE
changed mmcv version

### PR DESCRIPTION
**Pull request by aiarkinx**

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
@Iarkin please provide some reasoning, why is this change necessary?

**Comment by Iarkin** [comment]
> @Iarkin please provide some reasoning, why is this change necessary?

This PR fixes an error in validation tests

**Review by LeonidBeynenson — APPROVED** [review]

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson @aiarkinx we can't merge this PR until tests passed.

**Comment by LeonidBeynenson** [comment]
Ilya, Pavel, please do not merge this PR -- we decided not to increase the version of mmcv-full (we ound out how to avoid our issue by another way).
But, please, do not close this PR -- it is used by Anton @aiarkinx for some CI checks.

**Comment by aiarkinx** [comment]
run tests

**Pull request closed without merging**
